### ISSUE TITLE
How to add / remove an item from a list

### ISSUE THREAD

**Issue by callmekatootie** [graphcool/prisma-binding#117]
My Schema is as follows (using Prisma):

```
type User {
    ...
    follows: [User!]! @relation(name="Follows")
}
```

My question is how can I add an item to the follows attribute using the resolver function? I assume it to be something like:

```
context.query.db.updateUser({
    data: {
        follows:
            // I am stuck here, I don't know what property to use here to add a followers' userid
    }
});
```

I looked up the documentation but could not find information about this. Any hints?

**Comment by nikolasburk** [comment]
Hey @callmekatootie, if I understand correctly what you're looking for is a [nested mutation](https://www.prismagraphql.com/docs/reference/prisma-api/mutations-ol0yuoz6go#nested-mutations).

In your case, if the user does not exist yet, the mutation would have to be written as follows:

```graphql
mutation {
  updateUser(
    data: {
      follows: {
        create: {
          name: "asd"
          # ... potentially other required user fields
        }
      }
  } 
    where: {
      id: "__ID_OF_USER_TO_UPDATE"
    }
  ) {
    id
  }
}
```

If you want to add a `User` that already exists, you need to use `connect` instead of `create` and provide only the `id` of the other `User`:

```graphql
mutation {
  updateUser(
    data: {
      follows: {
        connect: {
          id: "__ID_OF_THE_USER_TO_BE_ADDED_TO_THE_LIST"
          # ... potentially other required user fields
        }
      }
  } 
    where: {
      id: "__ID_OF_USER_TO_UPDATE"
    }
  ) {
    id
  }
}
```

Let me know if that helps, otherwise I'll reopen the issue 🙂 Thanks!

**Comment by callmekatootie** [comment]
:+1: Thanks!

I actually did not expect `connect` to add to a list. I thought it was meant for more of a 1:1 kind of a relation and not for a 1:n but that totally worked for me. In case anybody comes across this ticket, then note that the procedure to remove an item from a list is to use `disconnect` - just as one would use `connect`.

**Comment by harshmangalam** [comment]
@callmekatootie nice  i have implement connect and disconnect in post and  user reactions many to many relation it work well
